- name: Install Python 3
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed


- name: Add Application User
  ansible.builtin.user:
    name: roboshop

- name: Remove old app content
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create app Directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download payment App content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/payment.zip
    dest: /app
    remote_src: yes

- name: Download Python Dependencies
  ansible.builtin.pip:
    requirements: /app/requirements.txt
    executable: pip3.6

- name: COpy SystemD file
  ansible.builtin.template:
    src: "catalogue.service"
    dest: /etc/systemd/system/payment.service

- name: Start payment Service
  ansible.builtin.systemd:
    name: "payment"
    daemon_reload: yes
    enabled: yes
    state: restarted