- name: Install the latest version of Apache
  ansible.builtin.dnf:
    name: httpd
    state: installed

- name:  remove pre-defined content of nginx
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent


- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: download frontend content and unzip
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Copy Nginx Config
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf


- name: Start service nginx, if not started
  ansible.builtin.service:
    name: nginx
    state: started
